version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.9-stretch-browsers
    environment:
        FLASK_APP: poll
        FLASK_ENV: production
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python -m pytest
  deploy:
    machine: true
    environment:
        FLASK_APP: poll
        FLASK_ENV: production
        
    steps:
      - checkout
      - heroku/install
      - run:
          name: List file
          command: |
            ls
      - run:
          name: Login into Heroku Docker Repository 
          command: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - heroku/push-docker-image:
        process-types: web
      - heroku/release-docker-image

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          process-types: web
          requires:
            - build-and-test
          filters:
            branches:
              only: production
